language: node_js
node_js:
  - "10"
branches:
  only:
  - master
install:
    - yarn install
script:
    - yarn build
deploy:
  provider: s3
  bucket: "notes.danielhan.dev"
  skip_cleanup: true
  acl: public_read
  local_dir: build
  region: "eu-north-1"
