language: node_js
node_js:
  - "10"
branches:
  only:
  - master
install:
    - yarn install
script:
    - yarn build
after_success:
    - aws s3 ls
    - git add .
    - git status
    - "git commit -m \"Update docs (travis build: $TRAVIS_BUILD_NUMBER)\""
    - git remote set-url origin https://${GITHUB_TOKEN}@github.com/hex0cter/notes.git
    - git push origin HEAD:master
