language: node_js
node_js:
  - "10"
branches:
  only:
  - master
install:
    - yarn install
script:
    - yarn build
# after_success:
#     - git add .
#     - git status
#     - "git commit -m \"Update docs (travis build: $TRAVIS_BUILD_NUMBER)\""
#     - git remote set-url origin https://${GITHUB_TOKEN}@github.com/hex0cter/notes.git
#     - git push origin HEAD:master
deploy:
  provider: s3
  access_key_id: "YOUR AWS ACCESS KEY"
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: "notes.danielhan.dev"
  skip_cleanup: false
  region: "eu-north-1"
