language: node_js
node_js:
  - "10"
branches:
  only:
  - master
install:
    - yarn install
script:
    - yarn build
    - ls
    - ls build
# after_success:
#     - git add .
#     - git status
#     - "git commit -m \"Update docs (travis build: $TRAVIS_BUILD_NUMBER)\""
#     - git remote set-url origin https://${GITHUB_TOKEN}@github.com/hex0cter/notes.git
#     - git push origin HEAD:master
deploy:
  provider: s3
  # access_key_id: "${AWS_ACCESS_KEY_ID}"
  # secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  bucket: "notes.danielhan.dev"
  skip_cleanup: false
  acl: public_read
  local_dir: "$PWD/build"
  region: "eu-north-1"
