language: node_js
node_js:
  - "10"
branches:
  only:
  - master
install:
    - yarn install
    - yarn build
script:
    - git add .
    - "git commit -m \"Update gh-pages (Travis build: $TRAVIS_BUILD_NUMBER)\""
after_success:
    - git push
